import type { Metadata } from "next";
import "./globals.css";
// import { Footer } from "@/components/Footer";
import { ReduxProvider } from "@/store/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="layout-container">
          <ReduxProvider>{children}</ReduxProvider>
          {/* TODO: list形式の表示画面が未実装のため、footerは非表示にする */}
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
